# Generated by Django 4.1.4 on 2022-12-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarShowRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Авто салон',
                'verbose_name_plural': 'Авто салоны',
                'db_table': 'car_showrooms',
            },
        ),
        migrations.CreateModel(
            name='CarSpecificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='car_showroom.carmodel', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика Автомобиля',
                'verbose_name_plural': 'Характеристики Автомобилей',
                'db_table': 'car_specification',
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='car_showroom.carshowroommodel', verbose_name='Авто салон'),
        ),
    ]
